name = "ts-webhook-proxy"
compatibility_date = "2025-09-04"

# Tell Wrangler this is a Pages project, not a Worker
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "SIGNALS"
id = "f4a5ae2d3cd04eefb912907ae27eb326"

[vars]
TS_WEBHOOK_SECRET = "my-strong-secret-123"
