name = "ts-webhook-proxy"
main = "functions/api/[[path]].ts"
compatibility_date = "2025-09-03"   # update to today’s date

[[kv_namespaces]]
binding = "SIGNALS"
id = "REPLACE_ME_AFTER_BINDING"

[vars]
TS_OPEN_URL_TEMPLATE = "https://charts.trendspider.com/?symbol={symbol}"
