name = "ts-webhook-proxy"
compatibility_date = "2024-09-04"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "SIGNALS"
id = "YOUR_NAMESPACE_ID_HERE"   # from `npx wrangler kv namespace list`
