name = "ts-webhook-proxy"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SIGNALS"
id = "REPLACE_ME_AFTER_BINDING"

[vars]
TS_OPEN_URL_TEMPLATE = "https://charts.trendspider.com/?symbol={symbol}"

